### ISSUE TITLE
Singleton pattern missing, intended?

### ISSUE THREAD

**Issue by aitorvs** [HeinrichReimer/android-inquiry#18]
#### Overview

the `init` static method does not enforce Singleton pattern.

``` java
    @NonNull
    public static Inquiry init(@NonNull Context context, @Nullable String databaseName,
                               @IntRange(from = 1, to = Integer.MAX_VALUE) int databaseVersion) {
        inquiry = new Inquiry(context, databaseName, databaseVersion);
        return inquiry;
    }
```

One could cal `Inquiry.init()` twice without `deinit`. Is this intended?
#### Proposed solution

Either:
1. `deinit` previous inquiry instance inside `init` method
2. Throw `IllegalStateException` when trying to re-`init`

**Comment by janheinrichmerker** [comment]
You are right about that. We should throw a IllegalStateException

**Comment by aitorvs** [comment]
Will prep a PR if you want.

**Comment by janheinrichmerker** [comment]
That'd be great. I commented on your original commit
